// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Routes$CoinadvisorUi = require("./root/Routes.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Routes$CoinadvisorUi.make(/* array */[])), "root");

ReasonReact.Router[/* push */0]("");

/*  Not a pure module */
