// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Root$CoinadvisorUi = require("./root/Root.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Root$CoinadvisorUi.make(/* array */[])), "root");

/*  Not a pure module */
